<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SqliteBrowser.Api</AssemblyName>
    <RootNamespace>SqliteBrowser.UI.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)Databases\Infra\SqliteBrowser.Infra\SqliteBrowser.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
