<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SqliteBrowser.UI</RootNamespace>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)Apps\Databases\Core\SqliteBrowser.Core\SqliteBrowser.Core.csproj" />
    <ProjectReference Include="$(SharedRoot)\Infra\Module\Shared.Infra.Module.Base\Shared.Infra.Module.Base.csproj" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.3.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
