CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE todo_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(500) NOT NULL,
    "Description" character varying(2000),
    "IsCompleted" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_todo_items" PRIMARY KEY (id)
);
COMMENT ON COLUMN todo_items.id IS 'Identificador único do item';
COMMENT ON COLUMN todo_items."Title" IS 'Título/tarefa do item';
COMMENT ON COLUMN todo_items."Description" IS 'Descrição opcional do item';
COMMENT ON COLUMN todo_items."IsCompleted" IS 'Indica se o item está concluído';
COMMENT ON COLUMN todo_items."CreatedAt" IS 'Data e hora de criação do item';
COMMENT ON COLUMN todo_items."UpdatedAt" IS 'Data e hora da última atualização do item';

CREATE INDEX "IX_todo_items_CreatedAt" ON todo_items ("CreatedAt");

CREATE INDEX "IX_todo_items_IsCompleted" ON todo_items ("IsCompleted");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216190505_20260216_160448', '10.0.3');

COMMIT;

