<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SqliteBrowser.Web</AssemblyName>
    <RootNamespace>SqliteBrowser.UI.Web</RootNamespace>
    <RazorLangVersion>Latest</RazorLangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)Apps\Databases\Core\SqliteBrowser.Core\SqliteBrowser.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
